---

- name: Disable selinux
  selinux:
    state: disabled

- name: Copy sysctl.conf
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
  notify: refresh sysctl

- name: Install libvirt
  yum:
    name: libvirt
    state: present
  notify: start libvirtd

- name: Install virt-install
  yum:
    name: virt-install
    state: present

- name: Install httpd
  yum:
    name: httpd
    state: present
  notify: start httpd

- name: Modify firewalld for httpd
  firewalld:
    service: http
    permanent: true
    state: enabled
  ignore_errors: yes

- name: make centos iso mount path
  file:
    path: " {{ centos_iso_mount_path }}"
    state: directory
  notify: mount CentOS ISO

- name: Check for Centos ISO
  shell: ls /mnt/ | grep -c {{ centos_iso_name }}
  register: CentOS_iso
  ignore_errors: yes

- name: download CentOS ISO
  get_url:
    url: "{{ uri_centos_iso }}"
    dest: /mnt
    validate_certs: no
    mode: 0644
  when: CentOS_iso.rc != 0
  notify: mount CentOS ISO

- name: Create inst symlink
  file:
    path: "/var/www/html/inst"
    src: "{{ centos_iso_mount_path }}"
    force: yes
    state: link
