---

- name: refresh sysctl
  command: sysctl -p

- name: start libvirtd
  service: name=libvirtd state=restarted enabled=yes

- name: start httpd
  service: name=httpd state=restarted enabled=yes

- name: mount CentOS ISO
  mount:
    name: "{{ centos_iso_mount_path }}"
    src: "/mnt/{{ centos_iso_name }}"
    fstype: iso9660
    opts: ro,loop
    state: mounted
