# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.network "private_network", ip: "192.168.122.2"
  config.vm.network "private_network", ip: "192.168.100.2"

  config.vm.provision "shell", inline: <<-SHELL
    ifup eth1
    ifup eth2
    chcon --reference /etc/sysconfig/network-scripts/ifcfg-eth0 /etc/sysconfig/network-scripts/ifcfg-eth{1,2}
    setenforce 1
    systemctl enable firewalld.service
    systemctl start firewalld.service
    reboot
  SHELL

end
