---

- name: refresh sysctl
  command: systemctl -p

- name: start libvirtd
  service: name=libvirtd state=restarted enabled=yes

- name: start httpd
  service: name=httpd state=restarted enabled=yes
