---

#- name: Enable ip_forward
#  lineinfile:
#    path: "/etc/sysctl.conf
#    line: 'net.ipv4.ip_forward=1'
#  notify: refresh sysctl

- name: Install Virtualization Host group
  yum:
    name: "@Virtualization Host"
    state: present
  notify: start libvirtd

- name: Install Virtualization Client group
  yum:
    name: "@Virtualization Client"
    state: present

- name: Install httpd
  yum:
    name: httpd
    state: present
  notify: start httpd
